[FEAT] added max_area problem
MIT-Emerging-Talent/ET6-foundations-group-23 pull request #40
Opened 2024-12-31 19:09 UTC by Urz1

---
name: solution review 
about: A template PR for code review with a checklist
---

## Behavior

### Files

- [x] The file name describes the function's behavior
- [x] There is a module docstring in the function file
- [x] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [x] There is a module docstring in the tests file

### Unit Tests

- [x] The test class has a helpful name in PascalCase
- [x] The test class has a docstring
- Every unit test has
  - [x] A helpful name
  - [x] A clear docstring
  - [x] Only one assertion
  - [x] There is no logic in the unit test
- [x] All tests pass
- [x] There are tests for defensive assertions
- [x] There are tests for boundary cases

### Function Docstring

- [x] The function's behavior is described
- The function's arguments are described:
  - [x] Type
  - [x] Purpose
  - [x] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [x] Type
  - [x] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [x] Each assumption about an argument is checked with an assertion
  - [x] Each assertion checks for _only one_ assumption about the argument
- [x] Include 3 or more (passing!) doctests

### The Function

- [x] The function's name describes it's behavior
- [x] The function's name matches the file name
- [x] The function has correct type annotations

## Strategy

### Do's

- [x] Variable names help to understand the strategy
- [x] Any comments are clear and describe the strategy
- [x] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [x] The function's strategy _is not_ described in the documentation
- [x] Comments explain the _strategy_, **not** the _implementation_
- [x] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [x] The code passes the formatting checks
- [x] The code passes all Ruff linting checks
- [x] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [x] Variables are named with snake_case
- [x] Variable names are clear and helpful
- [x] The code follows the strategy as simply as possible
- [x] The implementation is as simple as possible given the strategy
- [x] The code includes defensive assertions
- [x] Defensive assertions include as little logic as possible

2024-12-31 19:10 UTC, Urz1 commented
Check the problems solution.

2025-01-01 12:40 UTC, ciiyaa requested changes
Reviewed.

2025-01-01 12:40 UTC, ciiyaa commented on solutions/max_area.py
> +            16
Update **maxArea** to **max_area**

2025-01-01 12:40 UTC, ciiyaa commented on solutions/max_area.py
> +class Solution:
Missing a module docstring and header

2025-01-01 12:40 UTC, ciiyaa commented on solutions/tests/test_max_area.py
> +class test_max_area(unittest.TestCase):
Use PascalCase
```suggestion
class TestMaxArea(unittest.TestCase):
```

2025-01-01 12:40 UTC, ciiyaa commented on solutions/tests/test_max_area.py
> +import unittest
Missing a module docstring and header

2025-01-01 12:40 UTC, ciiyaa commented on solutions/tests/test_max_area.py
> +        """Test basic cases."""
A clear docstring specified for one test only

2025-01-01 12:40 UTC, ciiyaa commented on solutions/tests/test_max_area.py
> +        self.assertEqual(Solution().max_area([4, 3, 2, 1, 4]), 16)
Each test should have only one assertion

2025-01-01 12:40 UTC, ciiyaa commented on solutions/tests/test_max_area.py
For the unittests, each test should have **only one** assertion and a clear docstring describing a single case.

2025-01-01 12:40 UTC, ciiyaa commented on solutions/max_area.py
> +    def max_area(self, height):
Consider adding type annotations

2025-01-01 12:40 UTC, ciiyaa commented on solutions/max_area.py
> +            height (List[int]): A list of non-negative integers representing the height of walls.
```suggestion
            heights (List[int]): A list of non-negative integers representing the height of walls.
```

2025-01-01 14:58 UTC, ciiyaa commented on solutions/max_area.py
> +            # Move the pointer pointing to the shorter wall
This comment can be enhanced to explain the strategy

2025-01-01 14:59 UTC, ciiyaa commented on solutions/max_area.py
> +            # Calculate area with the current left and right pointers
This comment can be enhanced to explain the strategy

2025-01-01 16:06 UTC, ciiyaa reviewed
Refined the review.

2025-01-01 16:41 UTC, WuorBhang submitted a review, later dismissed

2025-01-02 20:27 UTC, Urz1 commented
@ciiyaa  Check it out i have included the suggestion and it's working well !. Thanks to point out this issues

2025-01-03 13:18 UTC, ciiyaa requested changes
Thank you for addressing the previous feedback and making the updates! While the code could be implemented without the _Solutions_ class, I understand this is a matter of personal preference, and the current approach works fine. I just have some suggestions to make the code align with the checklist.

2025-01-03 13:18 UTC, ciiyaa commented on solutions/max_area.py
> +    - maxArea: A function to compute the maximum area of water.
```suggestion
    - max_area: A function to compute the maximum area of water.
```

2025-01-03 13:18 UTC, ciiyaa commented on solutions/tests/test_max_area.py
> +        self.assertEqual(result, 0)  # Empty list
These can be split into two tests, each with only one assertion and a clear docstring.

2025-01-03 13:18 UTC, ciiyaa commented on solutions/tests/test_max_area.py
> +            self.solution.max_area([1, "a", 2])  # Non-integer in list
These defensive assertions should be split into 3 tests.

2025-01-03 14:12 UTC, Urz1 commented on solutions/max_area.py
> +    - maxArea: A function to compute the maximum area of water.
noted

2025-01-03 14:15 UTC, Urz1 commented on solutions/tests/test_max_area.py
> +        self.assertEqual(result, 0)  # Empty list
Noted!

2025-01-03 14:17 UTC, Urz1 commented on solutions/tests/test_max_area.py
> +            self.solution.max_area([1, "a", 2])  # Non-integer in list
Noted!

2025-01-03 14:22 UTC, Urz1 commented on solutions/max_area.py
The class structure provides a solid foundation.
Groups related functionality together, making it easier to organize and understand in a larger codebase. And it's one of the best practices and i would like my code to be structured this way.

2025-01-04 16:15 UTC, Urz1 commented on solutions/tests/test_max_area.py
> +        self.assertEqual(Solution().max_area([4, 3, 2, 1, 4]), 16)
noted

2025-01-04 16:17 UTC, Urz1 commented
I’ve incorporated all the suggestions and feedback you provided yesterday into this pull request. Thanks for your valuable insight they really helped improve the quality of the code. Could you please take another look and let me know if there’s anything else to address?

2025-01-05 18:12 UTC, ciiyaa approved these changes

2025-01-05 18:12 UTC, merged